### ISSUE TITLE
Important todo

### ISSUE THREAD

**Issue by SaveVic** [Project-PPL-MKOM/ppl-be-api#2]
- [ ] Change pose landmarker model to support heavy task (if possible)
- [x] Include image annotation in the response
- [x] Implement the detection task of real reference object
- [x] Adjust height calculation method
